In [1]:
print("hello")

hello


In [2]:
from numpy import *
arr1 = array([3,4,5,8])
print(arr1)


[3 4 5 8]


In [4]:
from numpy import *
arr2 = array([5,6,7])
arr3 = arr2
print (arr3)
print(type(arr3))


[5 6 7]
<class 'numpy.ndarray'>


In [5]:
from numpy import *
arr2 = array([5,6,7])
arr2 = arr2 + 5
print(arr2)

[10 11 12]


In [6]:
from numpy import *
arr2 = array([5,6,7])
arr3 = array([9,3,2])
arr4 = arr2 + arr3
print(arr4)

[14  9  9]


In [7]:
from numpy import *
arr2 = array([5,6,7])
print(sin(arr2))

[-0.95892427 -0.2794155   0.6569866 ]


In [8]:
from numpy import *
arr2 = array([5,6,7])
print(sum(arr2))

18


In [9]:
from numpy import *
arr2 = array([5,6,7])
print(sqrt(arr2))

[2.23606798 2.44948974 2.64575131]


In [10]:
from numpy import *
arr1 = array([5,6,7])
arr2 = array([7,8,9])
print(concatenate([arr1,arr2]))


[5 6 7 7 8 9]


In [12]:
from numpy import *
arr1 = array([
            [5,6,7],
            [4,5,6]
            ])
print (arr1.dtype)

int32
