In [1]:
print("hello")

hello


In [4]:
from numpy import *
arr1 = array([
             [1,3,6],
             [2,8,9]
            ])
print(arr1)
arr2 = arr1.flatten()
print(arr2)

[[1 3 6]
 [2 8 9]]
[1 3 6 2 8 9]


In [7]:
from numpy import *
arr1 = array([1,2,3,4,5,6])
arr2 = arr1.reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
from numpy import *
arr1 = array([
             [1,3,6],
             [2,8,9]
            ])
print(arr1[1,1])

8


In [11]:
from numpy import *
arr1 = array([
             [1,2,3,4,5,6],
             [7,8,9,10,11,12]
            ])
arr2 = arr1.flatten()
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
from numpy import *
arr1 = zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [14]:
from numpy import *
arr1 = ones(5,int)
print(arr1)

[1 1 1 1 1]


In [16]:
for i in range (1,5,1):
    print(i)

1
2
3
4


In [17]:
from numpy import *
arr1 = arange(1,15,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
from numpy import * 
arr1 = linspace(1,3,10)
print(arr1)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
